# config.py
# Auto-generated from config_template_user_input.xlsx
# Do not edit this file directly. Edit the Streamlit app or Excel template instead.

PROJECT_NAME = 'Multiple myeloma'

# Broad disease / field terms used to search PubMed.
SEARCH_TERMS = ['Multiple myeloma', 'cancer']

# Topic keywords used to score article relevance.
# Higher score = more important to the company/project.
RELEVANCE_TERMS = {'multiple myeloma': 10, 'cancer': 10, 'monoclonal gammopathy': 8}

# Outreach fit signals detected from author titles/journals.
OUTREACH_SIGNAL_TERMS = {'Custom Signals': ['therapeutic', 'mgus', 'precision medicine']}
OUTREACH_SIGNAL_WEIGHTS = {'Custom Signals': 9}

START_DATE = '2021/06/12'
END_DATE = '2026/06/11'

# Max PubMed papers to retrieve.
RETMAX = 300

# Minimum article relevance score to include an article/author in aggregation.
MIN_ARTICLE_SCORE = 10

# Author contribution weights.
AUTHOR_WEIGHTS = {
    "single": 1.0,
    "first": 0.8,
    "last": 0.9,
    "middle": 0.2,
}

# NCBI Entrez email.
NCBI_EMAIL = 'elynyu21@gmail.com'

# Output filenames. Usually do not change these.
PAPERS_SCORED_FILE = "papers_scored.csv"
AUTHOR_AGG_FILE = "author_aggregation.csv"
AUTHOR_AGG_V2_FILE = "author_aggregation_v2.csv"
AUTHOR_EMAIL_CANDIDATES_FILE = "author_email_candidates.csv"
AUTHOR_EMAIL_SUMMARY_FILE = "author_email_summary.csv"
AUTHOR_AFFILIATION_SUMMARY_FILE = "author_affiliation_summary.csv"
AUTHOR_MASTER_FILE = "author_aggregation_master.csv"
FINAL_XLSX = "outreach_rankings.xlsx"

# Backward-compatible aliases for older script versions.
AUTHOR_AGG_MASTER_FILE = AUTHOR_MASTER_FILE
FINAL_OUTPUT_FILE = FINAL_XLSX
